### ISSUE TITLE
Corrigir comando !caraio

### ISSUE THREAD

**Issue by rn4n** [pachicodes/deninho-bot#22]
Quando usado pela primeira vez, o bot responde:

```
Paxixa Códigos já falou caraio 1 vezes nessa live.
```

**TODO:**
- corrigir a palavra "vezes" conforme o valor do contador, ex:
  - (...) 0 vezes nessa live
  - (...) 1 vez nessa live
  - (...) 2 vezes nessa live
  - ....

**Comment by milafrn** [comment]
Irei fazer esta issue

**Comment by rn4n** [comment]
Mals @milafrn, fecharam a issue e quebraram o pipeline.
Mas obrigado pelo interesse em contribuir. 🤗

**Comment by milafrn** [comment]
;0 ;-; ok
