### ISSUE TITLE
Gender neutral

### ISSUE THREAD

**Issue by pachicodes** [pachicodes/deninho-bot#26]
Trocar palavras no masculine pelo representante neutro.
Tipo PACHI Foi Banides

**Comment by fsouza** [comment]
Acho que se der pra evitar palavras de gênero, é melhor ainda. Copia o pokemaobr e fala "pachi deu azar" ao invés de foi banido. Usar verbos com voz ativa ajuda também (e.g. "PACHI baniu Chico" ao invés de "Chico foi banido por pachi").

**Comment by fsouza** [comment]
(no momento, os comandos que precisam de ajuste são !ban e !duelo)

**Comment by caroldonadel** [comment]
vou fazer essa
